name: Tự động cập nhật số miền Bắc

on:
  schedule:
    - cron: '45 11 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mã nguồn
        uses: actions/checkout@v4

      - name: Thiết lập Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cài đặt thư viện
        run: pip install requests beautifulsoup4 pandas

      - name: Chạy script cào số
        # Ép robot đứng ở thư mục gốc để tìm file mienbac.py
        run: python mienbac.py
        working-directory: ./

      - name: Tự động đẩy file JSON lên GitHub
        run: |
          git config --global user.name "Robot SoMayMan"
          git config --global user.email "bot@somayman.top"
          git add data_bac.json
          git commit -m "Cập nhật kết quả ngày $(date)" || exit 0
          git push
